camel:
  springboot:
    name: MyCamel

    # keep Camel running
    main-run-controller: true

    # verbose summary so you can see the pairing of routes and routes configurations
    startup-summary-level: verbose